name: Run CI checks

on: pull_request

jobs:
  run_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check workflow files
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
        shell: bash
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Lint
        run: make lint

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Test
        run: make test

  test_load:
    runs-on: ubuntu-latest
    env:
      SERVER: "http://localhost:8888/v1"
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Build ingestion job container
        run:
          docker build -t cronjob:test .
      - name: Run local Remote Settings server
        run: |
          docker run --detach \
            --network=host \
            --env KINTO_INI=config/testing.ini \
            mozilla/remote-settings
      - name: Create collection
        run: |
          curl -X PUT http://localhost:8888/v1/buckets/main-workspace/collections/product-integrity

      - name: Run job from container
        run: |
          docker run -e SERVER="${SERVER}" \
            --network=host \
            cronjob:test

      - name: Run job from source
        run: make start
